concurrency:
  cancel-in-progress: false
  group: auto-merge-forward
jobs:
  count-open-dependabot-prs:
    name: Count Open Dependabot PRs
    outputs:
      prs_count: ${{ steps.count.outputs.prs_count }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      id: checkout
      name: Checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      env:
        GH_TOKEN: ${{ github.token }}
      id: count
      run: echo "prs_count=$(gh pr list --app dependabot --state open --json number
        --jq length)" >> $GITHUB_OUTPUT
  merge-forward:
    if: needs.count-open-dependabot-prs.outputs.prs_count == 0
    name: Merge Forward
    needs:
    - count-open-dependabot-prs
    permissions:
      contents: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      id: checkout
      name: Checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      id: setup-gh-user
      name: Setup GitHub User
      run: 'git config user.name ''github-actions[bot]''

        git config user.email ''github-actions[bot]@users.noreply.github.com''

        '
    - continue-on-error: true
      id: run-auto-merge-forward
      name: Run Merge Forward
      uses: marcusdacoregio/auto-merge-forward@9eac812bc73673e1a358766ac2ce319bd31ce0f8
      with:
        branches: 6.1.x, 6.2.x, main
        dry-run: false
        from-author: dependabot[bot]
name: Auto Merge Forward Dependabot PRs
on:
  repository_dispatch:
    types: trigger-ga___auto-merge-forward.yml
permissions:
  contents: read
